interface Commit {
  hash: string;
  fullHash: string;
  date: string;
  author: string;
  email: string;
  refs: string;
  subject: string;
  body: string;
}

const RECORD = "\x1e";
const FIELD = "\x1f";
const FORMAT = ["%h", "%H", "%aI", "%an", "%ae", "%D", "%s", "%b"].join(FIELD) + RECORD;
const ROOT = decodeURIComponent(new URL("../../", import.meta.url).pathname);
const DEFAULT_OUT = new URL("../git/", import.meta.url).pathname;

if (Deno.args.includes("--help") || Deno.args.includes("-h")) {
  console.log(`git:history — write Markdown files from Git commits

Usage:
  deno task git:history
  deno task git:history --limit 50 --since "3 months ago"
  deno task git:history --out _other/git

Options:
  --limit <n>     newest number of commits
  --since <when>  any value accepted by git log --since
  --out <dir>     output directory (default _other/git)`);
  Deno.exit(0);
}

const limitValue = flag("limit");
const limit = limitValue === null ? undefined : Number(limitValue);
if (limit !== undefined && (!Number.isInteger(limit) || limit <= 0)) {
  fail("--limit needs a positive whole number");
}

const since = flag("since") ?? undefined;
const outValue = flag("out");
const outDir = outValue ? resolveFromRoot(outValue) : DEFAULT_OUT;

try {
  const args = ["log", `--pretty=format:${FORMAT}`];
  if (limit) args.push(`-n${limit}`);
  if (since) args.push(`--since=${since}`);
  const command = await new Deno.Command("git", {
    args,
    cwd: ROOT,
    stdin: "null",
    stdout: "piped",
    stderr: "piped",
  }).output();
  if (!command.success) {
    throw new Error(new TextDecoder().decode(command.stderr).trim() || "git log failed");
  }

  const commits = parseCommits(new TextDecoder().decode(command.stdout));
  await Deno.mkdir(outDir, { recursive: true });
  await Deno.writeTextFile(`${outDir}/git-history.md`, renderHistory(commits, { limit, since }));
  await Deno.writeTextFile(`${outDir}/git-messages.md`, renderMessages(commits, { limit, since }));
  console.log(`wrote git-history.md and git-messages.md (${commits.length} commits)`);
} catch (error) {
  fail(error instanceof Error ? error.message : String(error));
}

function flag(name: string): string | null {
  const index = Deno.args.indexOf(`--${name}`);
  if (index >= 0) return Deno.args[index + 1] ?? null;
  const inline = Deno.args.find((argument) => argument.startsWith(`--${name}=`));
  return inline ? inline.slice(name.length + 3) : null;
}

function resolveFromRoot(path: string): string {
  if (path.startsWith("/")) return path;
  return new URL(path.replace(/^\.\//, ""), `file://${ROOT}/`).pathname;
}

function parseCommits(raw: string): Commit[] {
  return raw.split(RECORD).map((value) => value.trim()).filter(Boolean).map((value) => {
    const [
      hash = "",
      fullHash = "",
      date = "",
      author = "",
      email = "",
      refs = "",
      subject = "",
      body = "",
    ] = value.split(FIELD);
    return {
      hash,
      fullHash,
      date,
      author,
      email,
      refs,
      subject,
      body: body.replace(/^[\r\n]+/, "").replace(/\s+$/, ""),
    };
  });
}

function preamble(
  title: string,
  commits: Commit[],
  options: { limit?: number; since?: string },
): string[] {
  const scope = [
    options.since ? `since ${options.since}` : "",
    options.limit ? `last ${options.limit} commits` : "",
  ].filter(Boolean).join(", ");
  return [
    `# ${title}`,
    "",
    `Generated by \`deno task git:history\` on ${new Date().toISOString().slice(0, 10)}${
      scope ? ` (${scope})` : ""
    }. ${commits.length} commit${commits.length === 1 ? "" : "s"}.`,
    "",
    "Regenerate rather than edit; Git is the source of truth.",
    "",
  ];
}

function renderHistory(commits: Commit[], options: { limit?: number; since?: string }): string {
  const lines = preamble("Commit history", commits, options);
  let currentDay = "";
  for (const commit of commits) {
    const day = commit.date.slice(0, 10);
    if (day !== currentDay) {
      currentDay = day;
      lines.push(`## ${day}`, "");
    }
    lines.push(`- \`${commit.hash}\` ${commit.subject} — ${commit.author}`);
  }
  if (!commits.length) lines.push("No commits matched.");
  return `${lines.join("\n")}\n`;
}

function renderMessages(commits: Commit[], options: { limit?: number; since?: string }): string {
  const lines = preamble("Commit messages", commits, options);
  for (const commit of commits) {
    lines.push(
      `## ${commit.subject}`,
      "",
      `- commit: \`${commit.fullHash}\``,
      `- author: ${commit.author} <${commit.email}>`,
      `- date: ${commit.date}`,
    );
    if (commit.refs) lines.push(`- refs: ${commit.refs}`);
    lines.push("");
    if (commit.body) lines.push(commit.body, "");
    lines.push("---", "");
  }
  if (!commits.length) lines.push("No commits matched.");
  return `${lines.join("\n")}\n`;
}

function fail(message: string): never {
  console.error(`\x1b[31merror\x1b[0m ${message}`);
  Deno.exit(1);
}
